export type EsmaUlHusnaItem = {
    name: string;
    arabicName?: string;
    meaning: string;
    count: number;
};

export const ESMA_UL_HUSNA: EsmaUlHusnaItem[] = [
  { name: "Allah", arabicName: "الله", meaning: "Her şeyin yaratıcısı, eşi ve benzeri olmayan tek ilah.", count: 66 },
  { name: "Er-Rahman", arabicName: "الرَّحْمَنُ", meaning: "Dünyada bütün mahlukata merhamet eden, şefkat gösteren, ihsan eden.", count: 298 },
  { name: "Er-Rahim", arabicName: "الرَّحِيمُ", meaning: "Ahirette, sadece müminlere merhamet eden.", count: 258 },
  { name: "El-Melik", arabicName: "الْمَلِكُ", meaning: "Mülkün, kâinatın sahibi, mülk ve saltanatı devamlı olan.", count: 90 },
  { name: "El-Kuddüs", arabicName: "الْقُدُّوسُ", meaning: "Her noksanlıktan uzak ve her türlü takdise layık olan.", count: 170 },
  { name: "Es-Selam", arabicName: "السَّلاَمُ", meaning: "Her türlü tehlikelerden selamete çıkaran.", count: 131 },
  { name: "El-Mü'min", arabicName: "الْمُؤْمِنُ", meaning: "Güven veren, emin kılan, koruyan.", count: 137 },
  { name: "El-Müheymin", arabicName: "الْمُهَيْمِنُ", meaning: "Her şeyi görüp gözeten.", count: 145 },
  { name: "El-Aziz", arabicName: "الْعَزِيزُ", meaning: "İzzet sahibi, her şeye galip olan.", count: 94 },
  { name: "El-Cebbar", arabicName: "الْجَبَّارُ", meaning: "Azamet ve kudret sahibi. Dilediğini yapan ve yaptıran.", count: 206 },
  { name: "El-Mütekebbir", arabicName: "الْمُتَكَبِّرُ", meaning: "Büyüklükte eşi, benzeri olmayan.", count: 662 },
  { name: "El-Halık", arabicName: "الْخَالِقُ", meaning: "Yaratan, yoktan var eden.", count: 731 },
  { name: "El-Bari", arabicName: "الْبَارِئُ", meaning: "Her şeyi kusursuz ve uyumlu yaratan.", count: 214 },
  { name: "El-Musavvir", arabicName: "الْمُصَوِّرُ", meaning: "Varlıklara şekil veren.", count: 336 },
  { name: "El-Gaffar", arabicName: "الْغَفَّارُ", meaning: "Günahları örten ve çok mağfiret eden.", count: 1281 },
  { name: "El-Kahhar", arabicName: "الْقَهَّارُ", meaning: "Her şeye, her istediğini yapacak surette galip ve hakim olan.", count: 306 },
  { name: "El-Vehhab", arabicName: "الْوَهَّابُ", meaning: "Karşılıksız hibeler veren, çok fazla ihsan eden.", count: 14 },
  { name: "Er-Rezzak", arabicName: "الرَّزَّاقُ", meaning: "Bütün mahlukatın rızkını veren ve ihtiyacını karşılayan.", count: 308 },
  { name: "El-Fettah", arabicName: "الْفَتَّاحُ", meaning: "Her türlü müşkülleri açan ve kolaylaştıran, darlıktan kurtaran.", count: 489 },
  { name: "El-Alim", arabicName: "اَلْعَلِيمُ", meaning: "Gizli açık, geçmiş, gelecek, her şeyi en ince detaylarına kadar bilen.", count: 150 },
  { name: "El-Kabız", arabicName: "الْقَابِضُ", meaning: "Dilediğine darlık veren, sıkan, daraltan.", count: 903 },
  { name: "El-Basıt", arabicName: "الْبَاسِطُ", meaning: "Dilediğine bolluk veren, açan, genişleten.", count: 72 },
  { name: "El-Hafıd", arabicName: "الْخَافِضُ", meaning: "Dereceleri alçaltan.", count: 1481 },
  { name: "Er-Rafi", arabicName: "الرَّافِعُ", meaning: "Şeref verip yükselten.", count: 351 },
  { name: "El-Muiz", arabicName: "الْمُعِزُّ", meaning: "Dilediğini aziz eden, izzet veren.", count: 117 },
  { name: "El-Müzil", arabicName: "المُذِلُّ", meaning: "Dilediğini zillete düşüren.", count: 770 },
  { name: "Es-Semi", arabicName: "السَّمِيعُ", meaning: "Her şeyi en iyi işiten.", count: 180 },
  { name: "El-Basir", arabicName: "الْبَصِيرُ", meaning: "Gizli açık, her şeyi en iyi gören.", count: 302 },
  { name: "El-Hakem", arabicName: "الْحَكَمُ", meaning: "Mutlak hakim, hakkı batıldan ayıran. Hikmetle hükmeden.", count: 68 },
  { name: "El-Adl", arabicName: "الْعَدْلُ", meaning: "Mutlak adil, çok adaletli.", count: 104 },
  { name: "El-Latif", arabicName: "اللَّطِيفُ", meaning: "Lütuf ve ihsan sahibi olan. Bütün incelikleri bilen.", count: 129 },
  { name: "El-Habir", arabicName: "الْخَبِيرُ", meaning: "Olmuş olacak her şeyden haberdar.", count: 812 },
  { name: "El-Halim", arabicName: "الْحَلِيمُ", meaning: "Cezada, acele etmeyen, yumuşak davranan, hilm sahibi.", count: 88 },
  { name: "El-Azim", arabicName: "الْعَظِيمُ", meaning: "Büyüklükte benzeri yok. Pek yüce.", count: 1020 },
  { name: "El-Gafur", arabicName: "الْغَفُورُ", meaning: "Affı, mağfireti bol.", count: 1286 },
  { name: "Eş-Şekur", arabicName: "الشَّكُورُ", meaning: "Az amele, çok sevap veren.", count: 526 },
  { name: "El-Aliyy", arabicName: "الْعَلِيُّ", meaning: "Yüceler yücesi, çok yüce.", count: 110 },
  { name: "El-Kebir", arabicName: "الْكَبِيرُ", meaning: "Büyüklükte benzeri yok, pek büyük.", count: 232 },
  { name: "El-Hafiz", arabicName: "الْحَفِيظُ", meaning: "Her şeyi koruyucu olan.", count: 998 },
  { name: "El-Mukit", arabicName: "المُقِيتُ", meaning: "Rızıkları yaratan.", count: 550 },
  { name: "El-Hasib", arabicName: "الْحسِيبُ", meaning: "Kulların hesabını en iyi gören.", count: 80 },
  { name: "El-Celil", arabicName: "الْجَلِيلُ", meaning: "Celal ve azamet sahibi olan.", count: 73 },
  { name: "El-Kerim", arabicName: "الْكَرِيمُ", meaning: "Lütfü ve keremi bol, karşılıksız veren, çok ikram eden.", count: 270 },
  { name: "Er-Rakib", arabicName: "الرَّقِيبُ", meaning: "Her varlığı, her işi her an görüp, gözeten, kontrolü altında tutan.", count: 312 },
  { name: "El-Mucib", arabicName: "الْمُجِيبُ", meaning: "Duaları, istekleri kabul eden.", count: 55 },
  { name: "El-Vasi", arabicName: "الْوَاسِعُ", meaning: "Rahmet, kudret ve ilmi ile her şeyi ihata eden.", count: 137 },
  { name: "El-Hakim", arabicName: "الْحَكِيمُ", meaning: "Her işi hikmetli, her şeyi hikmetle yaratan.", count: 78 },
  { name: "El-Vedud", arabicName: "الْوَدُودُ", meaning: "Kullarını en çok seven, sevilmeye en layık olan.", count: 20 },
  { name: "El-Mecid", arabicName: "الْمَجِيدُ", meaning: "Her türlü övgüye layık bulunan.", count: 57 },
  { name: "El-Bais", arabicName: "الْبَاعِثُ", meaning: "Ölüleri dirilten.", count: 573 },
  { name: "Eş-Şehid", arabicName: "الشَّهِيدُ", meaning: "Her zaman her yerde hazır ve nazır olan.", count: 319 },
  { name: "El-Hakk", arabicName: "الْحَقُّ", meaning: "Varlığı hiç değişmeden duran. Var olan, hakkı ortaya çıkaran.", count: 108 },
  { name: "El-Vekil", arabicName: "الْوَكِيلُ", meaning: "Kendisine tevekkül edenlerin işlerini en iyi neticeye ulaştıran.", count: 66 },
  { name: "El-Kaviyy", arabicName: "الْقَوِيُّ", meaning: "Kudreti en üstün ve hiç azalmaz.", count: 116 },
  { name: "El-Metin", arabicName: "الْمَتِينُ", meaning: "Kuvvet ve kudret kaynağı, pek güçlü.", count: 500 },
  { name: "El-Veliyy", arabicName: "الْوَلِيُّ", meaning: "İnananların dostu, onları seven ve yardım eden.", count: 46 },
  { name: "El-Hamid", arabicName: "الْحَمِيدُ", meaning: "Her türlü hamd ve senaya layık olan.", count: 62 },
  { name: "El-Muhsi", arabicName: "الْمُحْصِيُ", meaning: "Yarattığı ve yaratacağı bütün varlıkların sayısını bilen.", count: 148 },
  { name: "El-Mubdi", arabicName: "المُبْدِئُ", meaning: "Maddesiz, örneksiz yaratan.", count: 57 },
  { name: "El-Muid", arabicName: "الْمُعِيدُ", meaning: "Yarattıklarını yok edip, sonra tekrar diriltecek olan.", count: 124 },
  { name: "El-Muhyi", arabicName: "الْمُحْيِيُ", meaning: "İhya eden, dirilten, can veren.", count: 68 },
  { name: "El-Mumit", arabicName: "اَلْمُمِيتُ", meaning: "Her canlıya ölümü tattıran.", count: 490 },
  { name: "El-Hayy", arabicName: "الْحَيُّ", meaning: "Ezeli ve ebedi hayat sahibi.", count: 18 },
  { name: "El-Kayyum", arabicName: "الْقَيُّومُ", meaning: "Varlıkları diri tutan, zatı ile kaim olan.", count: 156 },
  { name: "El-Vacid", arabicName: "الْوَاجِدُ", meaning: "Kendisinden hiçbir şey gizli kalmayan, istediğini, istediği vakit bulan.", count: 196 },
  { name: "El-Macid", arabicName: "الْمَاجِدُ", meaning: "Kadri ve şanı büyük, keremi, ihsanı bol olan.", count: 48 },
  { name: "El-Vahid", arabicName: "الْواحِدُ", meaning: "Zat, sıfat ve fiillerinde benzeri ve ortağı olmayan, tek olan.", count: 19 },
  { name: "Es-Samed", arabicName: "اَلصَّمَدُ", meaning: "Hiçbir şeye ihtiyacı olmayan, herkesin muhtaç olduğu.", count: 134 },
  { name: "El-Kadir", arabicName: "الْقَادِرُ", meaning: "Dilediğini dilediği gibi yaratmaya muktedir olan.", count: 305 },
  { name: "El-Muktedir", arabicName: "الْمُقْتَدِرُ", meaning: "Dilediği gibi tasarruf eden, her şeyi kolayca yaratan kudret sahibi.", count: 744 },
  { name: "El-Mukaddim", arabicName: "الْمُقَدِّمُ", meaning: "Dilediğini, öne alan, yükselten.", count: 184 },
  { name: "El-Muahhir", arabicName: "الْمُؤَخِّرُ", meaning: "Dilediğini sona alan, erteleyen, alçaltan.", count: 847 },
  { name: "El-Evvel", arabicName: "الأوَّلُ", meaning: "Ezeli olan, varlığının başlangıcı olmayan.", count: 37 },
  { name: "El-Ahir", arabicName: "الآخِرُ", meaning: "Ebedi olan, varlığının sonu olmayan.", count: 801 },
  { name: "Ez-Zahir", arabicName: "الظَّاهِرُ", meaning: "Yarattıkları ile varlığı açık, aşikar olan, kesin delillerle bilinen.", count: 1106 },
  { name: "El-Batın", arabicName: "الْبَاطِنُ", meaning: "Aklın tasavvurundan gizli olan.", count: 62 },
  { name: "El-Vali", arabicName: "الْوَالِيُ", meaning: "Bütün kâinatı idare eden.", count: 47 },
  { name: "El-Müteali", arabicName: "الْمُتَعَالِيُ", meaning: "Son derece yüce olan.", count: 551 },
  { name: "El-Berr", arabicName: "الْبَرُّ", meaning: "İyilik ve ihsanı bol, iyilik ve güzellik sahibi.", count: 202 },
  { name: "Et-Tevvab", arabicName: "التَّوَابُ", meaning: "Tövbeleri kabul edip, günahları bağışlayan.", count: 409 },
  { name: "El-Müntekim", arabicName: "الْمُنْتَقِمُ", meaning: "Asilerin, zalimlerin cezasını veren.", count: 630 },
  { name: "El-Afuvv", arabicName: "العَفُوُّ", meaning: "Affı çok olan, günahları affetmeyi seven.", count: 156 },
  { name: "Er-Rauf", arabicName: "الرَّءُوفُ", meaning: "Çok merhametli, pek şefkatli.", count: 287 },
  { name: "Malik-ül Mülk", arabicName: "مَالِكُ الْمُلْكِ", meaning: "Mülkün, her varlığın sahibi.", count: 212 },
  { name: "Zül-Celali vel İkram", arabicName: "ذُو الْجَلاَلِ وَالإكْرَام", meaning: "Celal, azamet ve pek büyük ikram sahibi.", count: 1100 },
  { name: "El-Muksit", arabicName: "الْمُقْسِطُ", meaning: "Her işi birbirine uygun yapan.", count: 209 },
  { name: "El-Cami", arabicName: "الْجَامِعُ", meaning: "Mahşerde her mahlukatı bir araya toplayan.", count: 114 },
  { name: "El-Ganiyy", arabicName: "الْغَنِيُّ", meaning: "Her türlü zenginlik sahibi, ihtiyacı olmayan.", count: 1060 },
  { name: "El-Mugni", arabicName: "المُغْنِيُ", meaning: "Müstağni kılan, ihtiyaç gideren, zengin eden.", count: 1100 },
  { name: "El-Mani", arabicName: "اَلْمَانِعُ", meaning: "Bir şeyin meydana gelmesine izin vermeyen, engelleyen.", count: 161 },
  { name: "Ed-Darr", arabicName: "الضَّارُّ", meaning: "Elem, zarar verenleri yaratan.", count: 1001 },
  { name: "En-Nafi", arabicName: "النَّافِعُ", meaning: "Fayda veren şeyleri yaratan.", count: 201 },
  { name: "En-Nur", arabicName: "النُّورُ", meaning: "Alemleri nurlandıran, dilediğine nur veren.", count: 256 },
  { name: "El-Hadi", arabicName: "الْهَادِيُ", meaning: "Hidayet veren.", count: 20 },
  { name: "El-Bedi", arabicName: "الْبَدِيعُ", meaning: "Eşi ve benzeri olmayan güzellikler yaratan.", count: 86 },
  { name: "El-Baki", arabicName: "اَلْبَاقِي", meaning: "Varlığının sonu olmayan, ebedi olan.", count: 113 },
  { name: "El-Varis", arabicName: "الْوَارِثُ", meaning: "Her şeyin asıl sahibi olan.", count: 707 },
  { name: "Er-Reşid", arabicName: "الرَّشِيدُ", meaning: "İrşada muhtaç olmayan, doğru yolu gösteren.", count: 514 },
  { name: "Es-Sabur", arabicName: "الصَّبُورُ", meaning: "Ceza vermede acele etmeyen.", count: 298 },
];
