export type EsmaUlHusnaItem = {
    name: string;
    meaning: string;
    count: number;
};

export const ESMA_UL_HUSNA: EsmaUlHusnaItem[] = [
    { name: "Allah", meaning: "Her şeyin yaratıcısı, eşi ve benzeri olmayan tek ilah.", count: 66 },
    { name: "Er-Rahman", meaning: "Dünyada bütün mahlukata merhamet eden, şefkat gösteren, ihsan eden.", count: 298 },
    { name: "Er-Rahim", meaning: "Ahirette, sadece müminlere merhamet eden.", count: 258 },
    { name: "El-Melik", meaning: "Mülkün, kâinatın sahibi, mülk ve saltanatı devamlı olan.", count: 90 },
    { name: "El-Kuddüs", meaning: "Her noksanlıktan uzak ve her türlü takdise layık olan.", count: 170 },
    { name: "Es-Selam", meaning: "Her türlü tehlikelerden selamete çıkaran.", count: 131 },
    { name: "El-Mü'min", meaning: "Güven veren, emin kılan, koruyan.", count: 137 },
    { name: "El-Müheymin", meaning: "Her şeyi görüp gözeten.", count: 145 },
    { name: "El-Aziz", meaning: "İzzet sahibi, her şeye galip olan.", count: 94 },
    { name: "El-Cebbar", meaning: "Azamet ve kudret sahibi. Dilediğini yapan ve yaptıran.", count: 206 },
    { name: "El-Mütekebbir", meaning: "Büyüklükte eşi, benzeri olmayan.", count: 662 },
    { name: "El-Halık", meaning: "Yaratan, yoktan var eden.", count: 731 },
    { name: "El-Bari", meaning: "Her şeyi kusursuz ve uyumlu yaratan.", count: 214 },
    { name: "El-Musavvir", meaning: "Varlıklara şekil veren.", count: 336 },
    { name: "El-Gaffar", meaning: "Günahları örten ve çok mağfiret eden.", count: 1281 },
    { name: "El-Kahhar", meaning: "Her şeye, her istediğini yapacak surette galip ve hakim olan.", count: 306 },
    { name: "El-Vehhab", meaning: "Karşılıksız hibeler veren, çok fazla ihsan eden.", count: 14 },
    { name: "Er-Rezzak", meaning: "Bütün mahlukatın rızkını veren ve ihtiyacını karşılayan.", count: 308 },
    { name: "El-Fettah", meaning: "Her türlü müşkülleri açan ve kolaylaştıran, darlıktan kurtaran.", count: 489 },
    { name: "El-Alim", meaning: "Gizli açık, geçmiş, gelecek, her şeyi en ince detaylarına kadar bilen.", count: 150 },
    { name: "El-Kabız", meaning: "Dilediğine darlık veren, sıkan, daraltan.", count: 903 },
    { name: "El-Basıt", meaning: "Dilediğine bolluk veren, açan, genişleten.", count: 72 },
    { name: "El-Hafıd", meaning: "Dereceleri alçaltan.", count: 1481 },
    { name: "Er-Rafi", meaning: "Şeref verip yükselten.", count: 351 },
    { name: "El-Muiz", meaning: "Dilediğini aziz eden, izzet veren.", count: 117 },
    { name: "El-Müzil", meaning: "Dilediğini zillete düşüren.", count: 770 },
    { name: "Es-Semi", meaning: "Her şeyi en iyi işiten.", count: 180 },
    { name: "El-Basir", meaning: "Gizli açık, her şeyi en iyi gören.", count: 302 },
    { name: "El-Hakem", meaning: "Mutlak hakim, hakkı batıldan ayıran. Hikmetle hükmeden.", count: 68 },
    { name: "El-Adl", meaning: "Mutlak adil, çok adaletli.", count: 104 },
    { name: "El-Latif", meaning: "Lütuf ve ihsan sahibi olan. Bütün incelikleri bilen.", count: 129 },
    { name: "El-Habir", meaning: "Olmuş olacak her şeyden haberdar.", count: 812 },
    { name: "El-Halim", meaning: "Cezada, acele etmeyen, yumuşak davranan, hilm sahibi.", count: 88 },
    { name: "El-Azim", meaning: "Büyüklükte benzeri yok. Pek yüce.", count: 1020 },
    { name: "El-Gafur", meaning: "Affı, mağfireti bol.", count: 1286 },
    { name: "Eş-Şekur", meaning: "Az amele, çok sevap veren.", count: 526 },
    { name: "El-Aliyy", meaning: "Yüceler yücesi, çok yüce.", count: 110 },
    { name: "El-Kebir", meaning: "Büyüklükte benzeri yok, pek büyük.", count: 232 },
    { name: "El-Hafiz", meaning: "Her şeyi koruyucu olan.", count: 998 },
    { name: "El-Mukit", meaning: "Rızıkları yaratan.", count: 550 },
    { name: "El-Hasib", meaning: "Kulların hesabını en iyi gören.", count: 80 },
    { name: "El-Celil", meaning: "Celal ve azamet sahibi olan.", count: 73 },
    { name: "El-Kerim", meaning: "Lütfü ve keremi bol, karşılıksız veren, çok ikram eden.", count: 270 },
    { name: "Er-Rakib", meaning: "Her varlığı, her işi her an görüp, gözeten, kontrolü altında tutan.", count: 312 },
    { name: "El-Mucib", meaning: "Duaları, istekleri kabul eden.", count: 55 },
    { name: "El-Vasi", meaning: "Rahmet, kudret ve ilmi ile her şeyi ihata eden.", count: 137 },
    { name: "El-Hakim", meaning: "Her işi hikmetli, her şeyi hikmetle yaratan.", count: 78 },
    { name: "El-Vedud", meaning: "Kullarını en çok seven, sevilmeye en layık olan.", count: 20 },
    { name: "El-Mecid", meaning: "Her türlü övgüye layık bulunan.", count: 57 },
    { name: "El-Bais", meaning: "Ölüleri dirilten.", count: 573 },
    { name: "Eş-Şehid", meaning: "Her zaman her yerde hazır ve nazır olan.", count: 319 },
    { name: "El-Hakk", meaning: "Varlığı hiç değişmeden duran. Var olan, hakkı ortaya çıkaran.", count: 108 },
    { name: "El-Vekil", meaning: "Kendisine tevekkül edenlerin işlerini en iyi neticeye ulaştıran.", count: 66 },
    { name: "El-Kaviyy", meaning: "Kudreti en üstün ve hiç azalmaz.", count: 116 },
    { name: "El-Metin", meaning: "Kuvvet ve kudret kaynağı, pek güçlü.", count: 500 },
    { name: "El-Veliyy", meaning: "İnananların dostu, onları seven ve yardım eden.", count: 46 },
    { name: "El-Hamid", meaning: "Her türlü hamd ve senaya layık olan.", count: 62 },
    { name: "El-Muhsi", meaning: "Yarattığı ve yaratacağı bütün varlıkların sayısını bilen.", count: 148 },
    { name: "El-Mubdi", meaning: "Maddesiz, örneksiz yaratan.", count: 57 },
    { name: "El-Muid", meaning: "Yarattıklarını yok edip, sonra tekrar diriltecek olan.", count: 124 },
    { name: "El-Muhyi", meaning: "İhya eden, dirilten, can veren.", count: 68 },
    { name: "El-Mumit", meaning: "Her canlıya ölümü tattıran.", count: 490 },
    { name: "El-Hayy", meaning: "Ezeli ve ebedi hayat sahibi.", count: 18 },
    { name: "El-Kayyum", meaning: "Varlıkları diri tutan, zatı ile kaim olan.", count: 156 },
    { name: "El-Vacid", meaning: "Kendisinden hiçbir şey gizli kalmayan, istediğini, istediği vakit bulan.", count: 196 },
    { name: "El-Macid", meaning: "Kadri ve şanı büyük, keremi, ihsanı bol olan.", count: 48 },
    { name: "El-Vahid", meaning: "Zat, sıfat ve fiillerinde benzeri ve ortağı olmayan, tek olan.", count: 19 },
    { name: "Es-Samed", meaning: "Hiçbir şeye ihtiyacı olmayan, herkesin muhtaç olduğu.", count: 134 },
    { name: "El-Kadir", meaning: "Dilediğini dilediği gibi yaratmaya muktedir olan.", count: 305 },
    { name: "El-Muktedir", meaning: "Dilediği gibi tasarruf eden, her şeyi kolayca yaratan kudret sahibi.", count: 744 },
    { name: "El-Mukaddim", meaning: "Dilediğini, öne alan, yükselten.", count: 184 },
    { name: "El-Muahhir", meaning: "Dilediğini sona alan, erteleyen, alçaltan.", count: 847 },
    { name: "El-Evvel", meaning: "Ezeli olan, varlığının başlangıcı olmayan.", count: 37 },
    { name: "El-Ahir", meaning: "Ebedi olan, varlığının sonu olmayan.", count: 801 },
    { name: "Ez-Zahir", meaning: "Yarattıkları ile varlığı açık, aşikar olan, kesin delillerle bilinen.", count: 1106 },
    { name: "El-Batın", meaning: "Aklın tasavvurundan gizli olan.", count: 62 },
    { name: "El-Vali", meaning: "Bütün kâinatı idare eden.", count: 47 },
    { name: "El-Müteali", meaning: "Son derece yüce olan.", count: 551 },
    { name: "El-Berr", meaning: "İyilik ve ihsanı bol, iyilik ve güzellik sahibi.", count: 202 },
    { name: "Et-Tevvab", meaning: "Tövbeleri kabul edip, günahları bağışlayan.", count: 409 },
    { name: "El-Müntekim", meaning: "Asilerin, zalimlerin cezasını veren.", count: 630 },
    { name: "El-Afuvv", meaning: "Affı çok olan, günahları affetmeyi seven.", count: 156 },
    { name: "Er-Rauf", meaning: "Çok merhametli, pek şefkatli.", count: 287 },
    { name: "Malik-ül Mülk", meaning: "Mülkün, her varlığın sahibi.", count: 212 },
    { name: "Zül-Celali vel İkram", meaning: "Celal, azamet ve pek büyük ikram sahibi.", count: 1100 },
    { name: "El-Muksit", meaning: "Her işi birbirine uygun yapan.", count: 209 },
    { name: "El-Cami", meaning: "Mahşerde her mahlukatı bir araya toplayan.", count: 114 },
    { name: "El-Ganiyy", meaning: "Her türlü zenginlik sahibi, ihtiyacı olmayan.", count: 1060 },
    { name: "El-Mugni", meaning: "Müstağni kılan, ihtiyaç gideren, zengin eden.", count: 1100 },
    { name: "El-Mani", meaning: "Bir şeyin meydana gelmesine izin vermeyen, engelleyen.", count: 161 },
    { name: "Ed-Darr", meaning: "Elem, zarar verenleri yaratan.", count: 1001 },
    { name: "En-Nafi", meaning: "Fayda veren şeyleri yaratan.", count: 201 },
    { name: "En-Nur", meaning: "Alemleri nurlandıran, dilediğine nur veren.", count: 256 },
    { name: "El-Hadi", meaning: "Hidayet veren.", count: 20 },
    { name: "El-Bedi", meaning: "Eşi ve benzeri olmayan güzellikler yaratan.", count: 86 },
    { name: "El-Baki", meaning: "Varlığının sonu olmayan, ebedi olan.", count: 113 },
    { name: "El-Varis", meaning: "Her şeyin asıl sahibi olan.", count: 707 },
    { name: "Er-Reşid", meaning: "İrşada muhtaç olmayan, doğru yolu gösteren.", count: 514 },
    { name: "Es-Sabur", meaning: "Ceza vermede acele etmeyen.", count: 298 },
];
